import type { TemplateMeta } from "../../types/Content";

// If you'd rather keep this as DB rows fetched at runtime, use templates.json
// with this file's shape (TemplateMeta) as the row type instead of importing
// this array directly.
export const templates: TemplateMeta[] = [
  {
    id: "modern-01",
    name: "Modern",
    category: "Modern",
    thumbnail: "/thumbnails/modern.svg",
    component: "ModernTemplate",
    layout: "sidebar-left",
    defaultTheme: {
      primaryColor: "#1F2A44",
      accentColor: "#C08A3E",
      backgroundColor: "#FFFFFF",
      textColor: "#1E1E1E",
      mutedColor: "#6B7280",
      headingFont: "Poppins",
      bodyFont: "Inter",
      fontScale: "md",
      radius: "md",
    },
    allowedFonts: ["Inter", "Poppins", "Roboto", "Merriweather"],
  },
  {
    id: "modern-02",
    name: "Modern Photo",
    category: "Modern",
    thumbnail: "/thumbnails/modern-02.jpg",
    component: "ModernPhotoTemplate",
    layout: "sidebar-left",
    defaultTheme: {
      primaryColor: "#2B2B2B",
      accentColor: "#F2A93B",
      backgroundColor: "#FFFFFF",
      textColor: "#2A2A2A",
      mutedColor: "#8A8A8A",
      headingFont: "Poppins",
      bodyFont: "Inter",
      fontScale: "md",
      radius: "none",
    },
    allowedFonts: ["Inter", "Poppins", "Roboto"],
  },
  {
    id: "minimal-02",
    name: "Minimal",
    category: "Minimal",
    thumbnail: "/thumbnails/minimal.svg",
    component: "MinimalTemplate",
    layout: "single-column",
    defaultTheme: {
      primaryColor: "#111111",
      accentColor: "#111111",
      backgroundColor: "#FFFFFF",
      textColor: "#1A1A1A",
      mutedColor: "#8A8A8A",
      headingFont: "Playfair Display",
      bodyFont: "Inter",
      fontScale: "md",
      radius: "none",
    },
    allowedFonts: ["Inter", "Playfair Display", "Roboto"],
  },
  {
    id: "professional-03",
    name: "Professional",
    category: "Professional",
    thumbnail: "/thumbnails/professional.svg",
    component: "ProfessionalTemplate",
    layout: "two-column",
    defaultTheme: {
      primaryColor: "#0B3B5C",
      accentColor: "#A98A3E",
      backgroundColor: "#FDFCFA",
      textColor: "#20242A",
      mutedColor: "#5B6470",
      headingFont: "Merriweather",
      bodyFont: "Roboto",
      fontScale: "md",
      radius: "sm",
    },
    allowedFonts: ["Merriweather", "Roboto", "Inter"],
  },
  {
    id: "business-04",
    name: "Business",
    category: "Business",
    thumbnail: "/thumbnails/business.svg",
    component: "BusinessTemplate",
    layout: "header-band",
    defaultTheme: {
      primaryColor: "#7A1F2B",
      accentColor: "#7A1F2B",
      backgroundColor: "#FFFFFF",
      textColor: "#1E1E1E",
      mutedColor: "#6B7280",
      headingFont: "Roboto Condensed",
      bodyFont: "Inter",
      fontScale: "md",
      radius: "none",
    },
    allowedFonts: ["Roboto Condensed", "Inter", "Poppins"],
  },
];